### PR TITLE
Bug Fix, Exponent Operator, Cast $exponent As Number To Avoid Infinite Loop

### PR DESCRIPTION
**Pull request by wbraswell**
Fixes https://github.com/adamkennedy/PPI/issues/229

### CODE REVIEW

**Comment by wbraswell** [comment]
Travis confirms this bug fix actually works in all versions of Perl, most importantly 5.24 and 5.26 which were previously failing.
https://travis-ci.org/wbraswell/physicsperl/builds/444291472
(Ignore false failures of "blead", that is a Travis problem.)

**Comment by wbraswell** [comment]
closed by request of haarg, will fix indenting and change from multiplication-by-one to addition-with-zero and open a new pull request

**Comment by wbraswell** [comment]
@adamkennedy 
Can you please review and merge this pull request?  Thanks!

**Comment by wchristian** [comment]
Thanks for the patch, i just released this to CPAN as https://metacpan.org/release/MITHALDU/PPI-1.242

**Pull request closed without merging**
