### PR TITLE
dzilification

### PR DESCRIPTION
**Pull request by karenetheridge**
at last!

version management is all automatic -- simply `dzil release` and the current version will be extracted from the main .pm module, the latest commit will be tagged, and then a new commit made on top which bumps the version ready for the next round of development.  (To perform a release using a different version, use the V environment variable = e.g. `V=2.000 dzil release` -- or you can change it in lib/PPPI.pm if you prefer.)

Some release test plugins are left commented out in dist.ini as they do not currently pass -- an exercise for a future pull request challenge, perhaps :)

### CODE REVIEW

**Comment by wchristian** [comment]
@karenetheridge Thank you so much for your work on this. I have something to request though. Would it be feasible to remove the version declarations from all or most modules and have it filled in at release time, to minimize churn?

I'm happy to do that part on my own if you'd rather i do that, and/or can give advice.

**Comment by karenetheridge** [comment]
I have now made that change -- the version is now calculated from the latest git tag (and is overrideable), and $VERSIONs are not kept in the in-repo .pm files, to minimize commit churn.

**Comment by wchristian** [comment]
Thanks for the work on this. It is merged and released as https://metacpan.org/release/MITHALDU/PPI-1.238

**Comment by karenetheridge** [comment]
\o/

**Pull request closed without merging**
