### PR TITLE
Support postfix dereference

### LINKED ISSUE #88: PPI recognize postfix dereference tokens incorrectly
tested with:

```
$sref->$*;
$aref->@*;
$aref->$#*;
$href->%*;
$cref->&*;
$gref->**;
```

### PR DESCRIPTION
**Pull request by akiym**
This resolves #88 

### `$foo->@*`

before:
```
PPI::Document
  PPI::Statement
    PPI::Token::Symbol          '$foo'
    PPI::Token::Operator        '->'
    PPI::Token::Magic   '@*'
```

after:
```
PPI::Document
  PPI::Statement
    PPI::Token::Symbol          '$foo'
    PPI::Token::Operator        '->'
    PPI::Token::Cast    '@*'
```

### `$foo->**`

before:
```
PPI::Document
  PPI::Statement
    PPI::Token::Symbol          '$foo'
    PPI::Token::Operator        '->'
    PPI::Token::Operator        '**'
```

after:
```
PPI::Document
  PPI::Statement
    PPI::Token::Symbol          '$foo'
    PPI::Token::Operator        '->'
    PPI::Token::Cast    '**'
```
### `$foo->%["bar"]`

before:
```
PPI::Document
  PPI::Statement
    PPI::Token::Symbol          '$foo'
    PPI::Token::Operator        '->'
    PPI::Token::Operator        '%'
    PPI::Structure::Constructor         [ ... ]
      PPI::Statement
        PPI::Token::Quote::Double       '"bar"'
```

after:
```
PPI::Document
  PPI::Statement
    PPI::Token::Symbol          '$foo'
    PPI::Token::Operator        '->'
    PPI::Token::Cast    '%'
    PPI::Structure::Subscript   [ ... ]
      PPI::Statement::Expression
        PPI::Token::Quote::Double       '"bar"'
```

### CODE REVIEW

**Comment by akiym** [comment]
@wchristian how about this p-r?

**Comment by xsawyerx** [comment]
Ping ping. Hitting this in an important case.

**Comment by wchristian** [comment]
You wouldn't want me to work on code today. Will review and merge+release tomorrow if it goes clean.

**Comment by wchristian** [comment]
Ok, got lost in a lot of release engineering stuff.

Put it up as a dev release: https://metacpan.org/release/MITHALDU/PPI-1.237_001

Please give it a good shakedown and let me know if it's good for you.

**Comment by wchristian** [comment]
I see two thumbs up, am i supposed to read those as "ran the code against our stuff and it works"?

**Comment by akiym** [comment]
Yes. PPI, Perl::Critic and App::PRT are working correctly to me and passed these tests on PPI@1.237_001.

**Comment by akiym** [comment]
Ping?

**Comment by xsawyerx** [comment]
@akiym This seems to be conflicting some files now. Any chance you could rebase it? It would make it much easier to merge.

**Comment by akiym** [comment]
@xsawyerx wchristian already cherry-picked into master for releasing 1.237_001 DEV. It's ready for 1.237!

**Comment by akiym** [comment]
cherry-picked by 902d4095c00c6689caaace4469cf51ed0feb25ab

**Pull request closed without merging**
