### PR TITLE
use our $VERSION rather than vars

### PR DESCRIPTION
**Pull request by karenetheridge**
Part of the dzilification project... but merging this now will make subsequent rebases much less painful.

### CODE REVIEW

**Comment by moregan** [comment]
When we no longer support running on 5.6.x...

**Comment by karenetheridge** [comment]
> When we no longer support running on 5.6.x...

Are you saying that `our` is incompatible with 5.6? Because that's not so.

**Comment by wchristian** [comment]
According to https://metacpan.org/pod/vars and current cpantesters matrices this does not change our backwards compat. Gonna merge it later. :)

**Comment by moregan** [comment]
Yes, I spoke too soon about when 'our' was introduced.

**Comment by wchristian** [comment]
@moregan That's fine, it happens. I'd rather see people speak up if it looks like i might mess up. :)

@karenetheridge Pushed your commit, and a handful of others that completely eradicate vars.pm, to master. Hope it helps your work!

**Pull request merged**
